#!/bin/bash

source ~/.bashrc
prevWall=$(cat ~/.cache/wal/wal)

files=($(find "$WALLDIR" -type f -printf '%P\n' | sort))

max_len=$(printf "%s\n" "${files[@]}" | awk '{ print length }' | sort -nr | head -n1)
width=$(( max_len * 7 ))

wallpaper=$(
	printf "%s\n" "${files[@]}" | \
	rofi -dmenu -i -theme-str "window { width: ${width}px; }" \
	-on-selection-changed "feh --bg-fill '$WALLDIR{entry}'")

if [ -z "$wallpaper" ]; then
	feh --bg-fill "$prevWall"
	exit 0
fi

feh --bg-fill "$WALLDIR$wallpaper"
wal -i "$WALLDIR$wallpaper" -n
xrdb -merge ~/.Xresources
notify-send "walled: $wallpaper"
