#!/usr/bin/env bash

search_dirs=(
  "$HOME/.dotfiles"
)

files=$(find "${search_dirs[@]}" -type f 2>/dev/null)

selected=$(printf '%s\n' "$files" | fzf --prompt="nve > ")

[ -n "$selected" ] && ${EDITOR:-nvim} "$selected"
