[mgr]
ratio               = [ 1, 2, 4 ]
show_hidden         = true
scrolloff           = 8
linemode            = "size"

[opener]
browser = [
  { run = 'xdg-open "$@"', desc = "Browser", orphan = true, for = "unix" }
]

[open]
prepend_rules = [
  { mime = "application/pdf", use = "browser" }
]
